### ISSUE TITLE
Hot-reloading doesn't work with symlinked plugin unless I do something in UI or run hot reload command explicitly

### ISSUE THREAD

**Issue by alex35mil** [pjeby/hot-reload#20]
When I change symlinked plugin's `main.js`, hot reload plugin doesn't detect the change unless I change something in Obsidian UI - eg, show/hide side bar.

When I run `Hot Reload: Check plugins for changes and reload them` from the command palette, it reloads the plugin.

My vault is in iCloud. 
I symlink the plugin into the `.obsidian/plugins` folder from my local folder and have `.hotreload` file in the root of the plugin directory.
I'm no macOS 14.6.1.
Obsidian Version 1.6.7 (Installer 1.4.16).
I pulled the hot reload plugin from the master yesterday.
I don't have Obsidian Sync enabled.
There's no such a problem with non-symlinked plugins.

**Comment by pjeby** [comment]
Type this into the developer console and press enter:

```js
app.plugins.plugins["hot-reload"].enabledPlugins
```

You should get a `Set()` object.  Click on the arrow next to to expand the list.  Is your plugin in that list?

**Comment by fractalpixel** [comment]
Seconding this, symlinked my plugin from the plugins directory of my testing Obsidian vault.  Hot reload doesn't seem to react to any changes in it.

The above code snippet lists both my plugin as well as hot-reload:

    Set(2) {'hot-reload', 'my-plugin'}

My OS is kubuntu 24.04, and my Obsidian version is 1.6.7.

As a workaround for now I just added a hotkey to the "reload app without saving" command which is pretty quick, but of course automated reloads would be neater.

**Comment by pjeby** [comment]
If you disable hot-reload and re-enable it, do any errors appear in the console?  Also, try adding a `console.log(filename)` to the start of the onFileChange() method -- do any filenames show up in the console when you change the plugin you're trying to get to reload?

**Comment by alex35mil** [comment]
> Is your plugin in that list?

Yup

> If you disable hot-reload and re-enable it, do any errors appear in the console?

Nope

> Also, try adding a console.log(filename) to the start of the onFileChange() method -- do any filenames show up in the console when you change the plugin you're trying to get to reload?

Nope. It shows up only when I hide sidebar - then plugin gets reloaded.

**Comment by alex35mil** [comment]
https://github.com/user-attachments/assets/1d14e286-84d8-4156-9d4b-7dad05c0bda6

**Comment by pjeby** [comment]
Huh.  And that's *with* the console.log added to the top of the onFileChange method?  I guess that explains the part where it's not triggering, but then why would the sidebar do anything?  That's weird.

What happens if you put the plugin in a non-iCloud directory and symlink to it?

**Comment by Asinphi** [comment]
My team members and I have an identical issue and we are on Windows 11, Obsidian v1.6.7. The plugin is in a regular directory, symlinked to the vault.

**Comment by pjeby** [comment]
Ah, okay, so my change to make things work on mobile broke symlinks on desktop.  I've released 0.1.13 with a fix.  (It turns out I didn't have as many symlinked plugins in my test vault as I thought I did -- that was on my *old* machine, not this one apparently.  In fact, my test vault currently has *no* symlinked plugins, even though I thought it had one.)

Upgrading to 0.1.13 should now fix the issue.

I partly figured out the sidebar thing - it's that any change to the workspace triggers Obsidian to save the workspace files, and then that *somehow* leads to it generating a `raw` event for the changed plugin file(s) despite the lack of a watch.  I have no idea how that works, it's kind of baffling.  But oh well, the actual bug is fixed now, upgrading should take care of it.

**Comment by nhannht** [comment]
Sorry, but it still not work on fedora-40, it just silent the debug error (so there is nothing for me to screenshot in debug console). Even when I manual trigger hot reload command the changes was not applied. This is version 0.1.13.
![image](https://github.com/user-attachments/assets/d3b283af-0cff-4132-b3c3-03d518daacfe)
